name: Example Workflow

on: [push]

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set execute permissions for script.sh
      run: chmod +x ./path/to/script.sh  # Adjust path if necessary

    - name: Run script.sh
      run: ./path/to/script.sh  # Adjust path if necessary
