name: Python Application Deployment

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Adjust according to your needs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        ls -R

    - name: Run Python script
      run: python src/hello.py
